#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define POWER_CHARGE_DETECT_PIN GPIO_NUM_21
#define POWER_ADC_UNIT ADC_UNIT_1
#define POWER_ADC_CHANNEL ADC_CHANNEL_3

#define RIGHT_LEG_PIN GPIO_NUM_5
#define RIGHT_FOOT_PIN GPIO_NUM_38
#define LEFT_LEG_PIN GPIO_NUM_17
#define LEFT_FOOT_PIN GPIO_NUM_18
#define LEFT_HAND_PIN GPIO_NUM_8
#define RIGHT_HAND_PIN GPIO_NUM_7

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_15
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_14
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_42
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_41
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_40

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_48
#define DISPLAY_MOSI_PIN GPIO_NUM_11
#define DISPLAY_CLK_PIN GPIO_NUM_12
#define DISPLAY_DC_PIN GPIO_NUM_16
#define DISPLAY_RST_PIN GPIO_NUM_6
#define DISPLAY_CS_PIN GPIO_NUM_39

#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH 280     // Đổi từ 240 thành 280 
#define DISPLAY_HEIGHT 240    // Đổi từ 280 thành 240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y true    // Đổi thành true
#define DISPLAY_SWAP_XY true     // Đổi thành true để xoay ngang
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 20      // Thêm offset để căn giữa
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 3

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define OTTO_ROBOT_VERSION "1.4.4"
#define AUDIO_INPUT_REFERENCE false  // Cho INMP441

#endif  // _BOARD_CONFIG_H_
